---

- name: Create Gitea Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: git
      spec: 

- name: Install Gitea Operator
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: redhat-gpte-gitea
        namespace: openshift-marketplace
      spec:
        sourceType: grpc
        image: quay.io/gpte-devops-automation/gitea-catalog:latest
        displayName: Red Hat GPTE (Gitea)
        publisher: Red Hat GPTE

- name: Install Gitea Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: gitea-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: gitea-operator
        source: redhat-gpte-gitea
        sourceNamespace: openshift-marketplace
        installPlanApproval: Automatic

- name: Check if Gtitea CRD is available
  command: oc get crd giteas.gpte.opentlc.com 
  register: crd_status
  retries: 60
  delay: 30
  until: crd_status.rc == 0

- name: Install Gitea Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: gpte.opentlc.com/v1
      kind: Gitea
      metadata:
        name: repository
        namespace: git
      spec:
        giteaImageTag: latest
        giteaSsl: true
        giteaVolumeSize: 4Gi
        postgresqlVolumeSize: 4Gi
        giteaAdminUser: gitea
        giteaAdminPassword: "gitea"
        giteaAdminEmail: opentlc-mgr@redhat.com
