---

- name: Create workshop-int Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: workshop-int
      spec:

- name: Install Pipelines Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-pipelines-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: openshift-pipelines-operator-rh
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        installPlanApproval: Automatic


