---

- name: Create quay Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: quay
      spec:

- name: Create Quay OperatorGroup
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-group.yml' ) | from_yaml }}"

- name: Install Quay Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/quay-operator.quay: ''
        name: quay-operator
        namespace: quay
      spec:
        channel: stable-3.7
        installPlanApproval: Automatic
        name: quay-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        startingCSV: quay-operator.v3.7.10

- name: Remove quay LimitRanges 
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      kind: LimitRange
      apiVersion: v1
      metadata:
        name: quay-core-resource-limits
        namespace: quay
      spec:
        limits:
          - type: Container
            max:
              cpu: '4'
              memory: 6Gi
            default:
              cpu: 500m
              memory: 1536Mi
            defaultRequest:
              cpu: 50m
              memory: 256Mi
          - type: Pod
            max:
              cpu: '4'
              memory: 12Gi

- name: "Wait for ODF Storagesystem to be ready"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: "odf.openshift.io/v1alpha1"
    kind: StorageSystem
    name: ocs-storagecluster-storagesystem
    wait: true
    wait_condition:
      reason: Reconciling
      status: 'True'
      type: Progressing
    wait_sleep: 10
    wait_timeout: 360

- name: Install Quay Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: quay.redhat.com/v1
      kind: QuayRegistry
      metadata:
        name: quay
        namespace: quay
      spec:
        components:
          - kind: clair
            managed: true
          - kind: postgres
            managed: true
          - kind: objectstorage
            managed: true
          - kind: redis
            managed: true
          - kind: horizontalpodautoscaler
            managed: true
          - kind: route
            managed: true
          - kind: mirror
            managed: true
          - kind: tls
            managed: true
          - kind: quay
            managed: true
          - kind: clairpostgres
            managed: true

- name: Include Quay Bridge Operator
  include_tasks: "install-quay-bridge.yml"
  when:  install_quay_bridge


