- name: Install Quay Bridge Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'quay-bridge-operator.yml' ) | from_yaml }}"
  tags:
    - quay


- name: "Get Installed CSV"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "quay-bridge-operator"
    namespace: "quay"
  register: r_subscription
  retries: 30
  delay: 5
  until:
    - r_subscription.resources[0].status.currentCSV is defined
    - r_subscription.resources[0].status.currentCSV | length > 0
  tags:
    - quay

- name: "Wait until CSV is installed"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "quay"
  register: r_csv
  retries: 30
  delay: 30
  until:
    - r_csv.resources[0].status.phase is defined
    - r_csv.resources[0].status.phase | length > 0
    - r_csv.resources[0].status.phase == "Succeeded"
  tags:
    - quay

- name: Get route for Quay instance
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Route
    namespace: "quay"
    name: "quay-quay"
  register: quay_instance_route
  changed_when: false
  retries: 15
  delay: 10
  until: quay_instance_route.resources | list | length == 1
  tags:
    - quay


- name: Create variable with Quay route
  set_fact:
    quay_instance_route: "https://{{ quay_instance_route.resources[0].spec.host }}"
  tags:
    - quay

- name: Install Quay Bridge Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('template', 'quay-bridge-instance.yml' ) | from_yaml }}"
  tags:
    - quay

